import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/components/utils/providers";
import { AppSidebar } from "@/components/modules/app-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" async /> */}
      </head>
      <body>
        <Providers>
          <AppSidebar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
